services:
  - type: web
    name: kiro-rs
    runtime: image
    image:
      url: ghcr.io/hopesy/kiro-rs:v2026.3.6
    plan: free
    autoDeploy: false
    envVars:
      - key: GIT_STORAGE_REPO_URL
        sync: false
      - key: GIT_STORAGE_AUTH_TOKEN
        sync: false
      - key: PUBLIC_API_KEY
        sync: false
      - key: ADMIN_API_KEY
        sync: false
      - key: KIRO_REGION
        sync: false
    startCommand: /app/kiro-rs
