services:
  - type: web
    name: kiro-rs
    runtime: image
    image:
      url: ghcr.io/hopesy/kiro-rs:v2026.3.4
    plan: free
    autoDeploy: false
    envVars:
      - key: GIT_STORAGE_REPO_URL
        sync: false
      - key: GIT_STORAGE_AUTH_TOKEN
        sync: false
    startCommand: /app/kiro-rs -c /app/config/config.json --credentials /app/config/credentials.json
